### ISSUE TITLE
remove all keys and secrets

### ISSUE THREAD

**Issue by gregziegan** [morgworth/TWC-side-project#12]
Keys and secrets should _never_ be in your source code. This is a security vulnerability. Please read these in from environment variables.

https://github.com/morgworth/TWC-side-project/blob/47188fb16ebe00cb3474f5c17dd432f72cf76c44/strike_pledge/pledge/views.py#L56-L60

After fixing it, i would even recreate the repository or force-push those commits away otherwise people can still find it going through old commits

**Comment by morgworth** [comment]
Thanks for the heads up. The current project is set to private for the time being. I could set up a table in the db to get those values. I'm not sure I can do that in the next few days though. Thanks for the heads up.

**Comment by morgworth** [comment]
I have removed the keys from the source code and added them as environment variables in the settings file.
