### ISSUE TITLE
SQLLite DB shouldn't be committed

### ISSUE THREAD

**Issue by gregziegan** [morgworth/TWC-side-project#4]
No data should be committed to the git repository. I would add it to `.gitignore`.

If you need seeddata, i'd recommend writing it in JSON, YAML, or python and creating a test and dev database via a small script (python, bash, whatever).

**Comment by gregziegan** [comment]
This _can_ be a security vulnerability if you accidently commit any real passwords that you'll use on the deployed instance. Best to not let that be possible

**Comment by morgworth** [comment]
Thanks. Yeah this db is only for testing purposes. The real db will be on Amazon RDS.
