### ISSUE TITLE
Prefer <button/> for click behavior instead of links

### ISSUE THREAD

**Issue by gregziegan** [morgworth/TWC-side-project#7]
https://github.com/morgworth/TWC-side-project/blob/47188fb16ebe00cb3474f5c17dd432f72cf76c44/strike_pledge/templates/about.html#L91

No need to add `javascript:void(0)` if the element is a button.

**Comment by morgworth** [comment]
I changed it over to button and tried to apply the same CSS but couldn't get the styling right. Since it is a tight deadline, I'll stick with the anchor tag.
