### ISSUE TITLE
Consolidate copy-pasted JavaScript

### ISSUE THREAD

**Issue by gregziegan** [morgworth/TWC-side-project#8]
https://github.com/morgworth/TWC-side-project/blob/47188fb16ebe00cb3474f5c17dd432f72cf76c44/strike_pledge/templates/email.html#L8-L19

Let's move this into `navPositioning.js`

And then you use `<script src="navPositioning.js" />` instead of copy-pasting the same 10 lines in several files

**Comment by morgworth** [comment]
I have added it to a file called scripts.js
Thankfully, unlike for the css, nothing is changed by copying it over to the static folder and including it.
