### ISSUE TITLE
Consolidate copy-pasted navbar CSS

### ISSUE THREAD

**Issue by gregziegan** [morgworth/TWC-side-project#9]
https://github.com/morgworth/TWC-side-project/blob/47188fb16ebe00cb3474f5c17dd432f72cf76c44/strike_pledge/templates/about.html#L28-L78

Let's move all of this into `navbar.css` and then do `<link rel="stylesheet" href="navbar.css"/>` to re-use these 50 lines of code in all the pages you want it (by using `<link />`.

**Comment by gregziegan** [comment]
Ah i see you already have `styles.css` with these values... Any reason you're not including it with `<link />`?

**Comment by morgworth** [comment]
It has to do with how django handles static files. I probably should do that on best practices grounds but it's functional. I'll look more into it.

**Comment by morgworth** [comment]
I tried linking it but for some reason, just copying and pasting the styling from the style tag to a file and then linking it messes with the format. I'll just leave it as is.
